# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cb8bc22ac5d662f3278296e43e69e8fd"
name = "shopping-assistant"
handle = "shopping-assistant-7"
application_url = "https://arctic-appearance-everybody-enemies.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "super-store-boost-2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://arctic-appearance-everybody-enemies.trycloudflare.com/auth/callback",
  "https://arctic-appearance-everybody-enemies.trycloudflare.com/auth/shopify/callback",
  "https://arctic-appearance-everybody-enemies.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
